
version: '3.8' # Sử dụng phiên bản Docker Compose file format mới nhất

services:
  # Dịch vụ MySQL Database
  mysql:
    image: mysql:8.0 # Sử dụng MySQL 8.0 image
    container_name: mysql_db # Tên container dễ nhận diện
    environment: # Các biến môi trường cho MySQL
      MYSQL_ROOT_PASSWORD: LuongLuvWinnerX2004 # Đã cập nhật để khớp với application.properties
      MYSQL_DATABASE: chembridge # Đã cập nhật để khớp với database của bạn
    ports:
      - "3306:3306" # Mở cổng MySQL ra bên ngoài (tùy chọn, chỉ cần nếu bạn muốn truy cập từ host)
    volumes:
      - mysql_data:/var/lib/mysql # Volume để lưu trữ dữ liệu MySQL bền vững
      # Copy file dump SQL của bạn vào thư mục khởi tạo MySQL
      - ./my_database_dump.sql:/docker-entrypoint-initdb.d/my_database_dump.sql
      # Thêm script để cấp quyền cho user root từ mọi host
      - ./init_grants.sql:/docker-entrypoint-initdb.d/init_grants.sql # Dòng mới được thêm
    healthcheck: # Thêm Healthcheck để đảm bảo MySQL đã sẵn sàng
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pLuongLuvWinnerX2004"] # Đã cập nhật user/pass
      interval: 5s # Kiểm tra mỗi 5 giây
      timeout: 5s # Timeout sau 5 giây nếu không phản hồi
      retries: 20 # Tăng số lần thử lại để MySQL có thêm thời gian
      start_period: 60s # Tăng thời gian chờ ban đầu lên 60 giây (hoặc hơn nếu database lớn)
    networks:
      - app_network # Kết nối vào mạng riêng của ứng dụng

  # Dịch vụ Spring Boot Backend
  backend:
    build:
      context: ./backend # Chỉ định thư mục chứa Dockerfile của backend
      dockerfile: Dockerfile # Tên Dockerfile (mặc định là Dockerfile)
    container_name: springboot_backend
    ports:
      - "8080:8080" # Ánh xạ cổng 8080 của container ra cổng 8080 của host
    environment: # Các biến môi trường cho Spring Boot backend
      # Kết nối đến database MySQL bên trong mạng Docker Compose
      # 'mysql' là tên dịch vụ của MySQL trong docker-compose.yml
      DB_URL: jdbc:mysql://mysql:3306/chembridge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC # Đã cập nhật tên database
      DB_USERNAME: root # Đã cập nhật user
      DB_PASSWORD: LuongLuvWinnerX2004 # Đã cập nhật pass
      SPRING_PROFILES_ACTIVE: prod # Kích hoạt profile production (nếu bạn có)
    depends_on: # Đảm bảo MySQL khởi động và khỏe mạnh trước backend
      mysql:
        condition: service_healthy
    networks:
      - app_network

  # Dịch vụ ReactJS Frontend (được phục vụ bởi Nginx)
  frontend:
    build:
      context: ./frontend # Chỉ định thư mục chứa Dockerfile của frontend
      dockerfile: Dockerfile # Tên Dockerfile (mặc định là Dockerfile)
    container_name: react_frontend
    ports:
      - "80:80" # Ánh xạ cổng 80 của container (Nginx) ra cổng 80 của host (truy cập qua HTTP)
      # Nếu bạn muốn HTTPS sau này, bạn sẽ cấu hình Nginx hoặc dùng reverse proxy khác (ví dụ: Caddy, Certbot)
    depends_on: # Đảm bảo backend khởi động trước frontend (nếu frontend cần backend để build/khởi động)
      - backend
    networks:
      - app_network

# Định nghĩa các Volumes để lưu trữ dữ liệu bền vững
volumes:
  mysql_data: # Volume cho dữ liệu MySQL

# Định nghĩa mạng nội bộ để các container giao tiếp
networks:
  app_network:
    driver: bridge
