-- Insert into question_list table
INSERT INTO question_list (attempts, duration, question_list_id, category, description, difficulty, question_count, title)
VALUES (0, 60, 1, 'Hóa học', 'Các bài tập về xác định độ pH', 'Trung bình', '67', 'Xác định pH');

INSERT INTO questions (answer, question_list_id, question) VALUES
(0, 1, 'Dung dịch X có pH=12, thì [OH⁻] của dung dịch là'),
(1, 1, 'Dung dịch H₂SO₄ 0,10 M có'),
(0, 1, 'pH của hỗn hợp dung dịch HCl 0,005 M và H₂SO₄ 0,0025 M là'),
(3, 1, 'Hòa tan 4,9 mg H₂SO₄ vào nước thu được 1 lít dung dịch. pH của dung dịch thu được là'),
(0, 1, 'pH của dung dịch Ba(OH)₂ 0,05 M là'),
(2, 1, 'Cần bao nhiêu gam NaOH để pha chế 250 ml dung dịch có pH=10'),
(2, 1, 'Số ml dung dịch NaOH có pH=12 cần để trung hòa 10 ml dung dịch HCl có pH=1 là'),
(2, 1, 'Cho 15 ml dung dịch HNO₃ có pH=2 trung hòa hết 10 ml dung dịch Ba(OH)₂ có pH = a. Giá trị của a là'),
(0, 1, 'Hòa tan m gam Zn vào 100 ml dung dịch H₂SO₄ 0,4 M thu được 0,784 lít khí H₂ và dung dịch X. Tính pH của dung dịch X'),
(1, 1, 'A là dung dịch HNO₃ 0,01 M; B là dung dịch H₂SO₄ 0,005 M. Trộn các thể tích bằng nhau của A và B được dung dịch X. Tính pH của dung dịch X'),
(0, 1, 'Dung dịch HCl 0,001 M có pH bằng'),
(1, 1, 'Dung dịch đệm gồm 0,1 M CH₃COOH (Ka=1.8×10⁻⁵) và 0,1 M CH₃COONa. pH của dung dịch là'),
(1, 1, 'Dung dịch đệm CH₃COOH/CH₃COONa có pH ban đầu là 4,75. Khi thêm 0,01 mol HCl vào 1 lít dung dịch, pH thay đổi như thế nào'),
(1, 1, 'Dung dịch HCl 0,01 M có pH xấp xỉ là'),
(2, 1, 'Dung dịch nào sau đây có pH<7 do sự thủy phân'),
(0, 1, 'Dung dịch CH₃COOH 0,1 M có độ điện li α=0,01. Nồng độ ion H⁺ là'),
(0, 1, 'Dung dịch H₂SO₄ 0,1 M có'),
(1, 1, 'Công thức tính pH của một dung dịch là'),
(0, 1, 'Một dung dịch có pH=3 thì môi trường của dung dịch đó là'),
(0, 1, 'Trong dung dịch trung tính ở 25°C, nồng độ ion H⁺ là'),
(1, 1, 'Khi thêm acid vào nước, pH của dung dịch sẽ'),
(1, 1, 'Nếu nồng độ OH⁻ trong dung dịch là 10⁻² M, thì pOH của dung dịch đó là bao nhiêu'),
(2, 1, 'Mối quan hệ giữa pH và pOH ở 25°C là'),
(2, 1, 'Chất nào sau đây là acid mạnh'),
(3, 1, 'Dung dịch có pH=13 thì môi trường của dung dịch đó là'),
(1, 1, 'Nước nguyên chất ở 25°C có pH bằng'),
(0, 1, 'Khi nồng độ H⁺ tăng 10 lần, pH sẽ'),
(1, 1, 'Dung dịch nào sau đây có pH lớn nhất'),
(1, 1, 'Dụng cụ nào sau đây được dùng để đo pH một cách chính xác nhất'),
(0, 1, 'Nếu một dung dịch có pOH=9, thì pH của dung dịch đó là'),
(2, 1, 'Để xác định pH một cách nhanh chóng và tương đối, có thể dùng'),
(1, 1, 'Trong các dung dịch có cùng nồng độ mol sau đây, dung dịch nào có pH nhỏ nhất'),
(2, 1, 'pH của một dung dịch HNO₃ 0.001 M là'),
(0, 1, 'Khi pha loãng một dung dịch acid, pH của dung dịch sẽ'),
(2, 1, 'Dung dịch đệm là'),
(2, 1, 'Dung dịch chứa cặp chất nào sau đây tạo thành dung dịch đệm'),
(2, 1, 'Dung dịch đệm không được tạo thành từ cặp chất nào sau đây'),
(2, 1, 'pH của dung dịch đệm được tính theo công thức'),
(1, 1, 'Dung dịch gồm CH₃COOH 0,1 M và CH₃COONa 0,1 M có pKa=4,75. Tính pH'),
(3, 1, 'Thêm vài giọt NaOH vào dung dịch đệm CH₃COOH/CH₃COONa sẽ'),
(2, 1, 'Muốn tạo dung dịch đệm có pH xấp xỉ 9, nên chọn cặp chất nào'),
(2, 1, 'Dung dịch đệm hoạt động hiệu quả nhất khi'),
(0, 1, 'Dung dịch gồm NH₃ 0,1 M và NH₄Cl 0,1 M có pKb=4,75. Tính pH'),
(3, 1, 'Dung dịch đệm nào sau đây có pH<7'),
(3, 1, 'Điều nào sau đây sai về dung dịch đệm'),
(2, 1, 'Chất nào sau đây không tham gia tạo dung dịch đệm'),
(2, 1, 'Muốn pha 100 ml dung dịch đệm pH=5 từ CH₃COOH và CH₃COONa, cần'),
(1, 1, 'Dung dịch đệm có pKa=4,75 và tỷ lệ [base]/[acid]=10. Tính pH'),
(2, 1, 'Chức năng của dung dịch đệm trong cơ thể người là'),
(2, 1, 'Dung dịch đệm chỉ có thể hoạt động khi'),
(0, 1, 'Dung dịch đệm tốt nhất khi'),
(2, 1, 'Hằng số Ka càng nhỏ thì'),
(1, 1, 'pH của dung dịch càng lớn thì tính acid càng mạnh'),
(1, 1, 'Mọi chất chỉ thị acid-base đều có thể dùng để đo pH một cách chính xác'),
(1, 1, 'Khi nồng độ ion H⁺ là 10⁻⁵ M, dung dịch có tính base'),
(1, 1, 'Trong mọi dung dịch nước, tích số nồng độ H⁺ và OH⁻ luôn không đổi'),
(1, 1, 'pH của dung dịch acid yếu luôn nhỏ hơn pH của dung dịch acid mạnh có cùng nồng độ'),
(0, 1, 'Máy đo pH cần được hiệu chuẩn trước khi sử dụng để đảm bảo độ chính xác'),
(0, 1, 'Dung dịch muối được tạo thành từ acid mạnh và base yếu sẽ có pH<7'),
(0, 1, 'Khi pH của một dung dịch thay đổi từ 6 xuống 4, nồng độ H+ đã tăng 100 lần'),
(0, 1, 'Nước mưa tự nhiên có pH < 7 là do có hòa tan CO2​.'),
(1, 1, 'Acid Bronsted-Lowry là chất nhận proton'),
(1, 1, 'Base Bronsted-Lowry là chất cho proton'),
(1, 1, 'Phenolphtalein đổi màu từ không màu sang hồng trong môi trường acid'),
(0, 1, 'Độ điện li của acid mạnh là 100%'),
(0, 1, 'Dung dịch đệm là dung dịch có khả năng duy trì pH ổn định khi thêm một lượng nhỏ acid hoặc base'),
(1, 1, 'Giá trị pOH của một dung dịch có thể âm');

-- Insert into options table (Multiple Choice Questions 1-52)
INSERT INTO options (option_id, question_id, content) VALUES
(1, 1, '0,01 M'), (2, 1, '1,2 M'), (3, 1, '0,12 M'), (4, 1, '0,20 M'),
(5, 2, 'pH=1'), (6, 2, 'pH<1'), (7, 2, 'pH>1'), (8, 2, '[H⁺]>2,0 M'),
(9, 3, '2'), (10, 3, '3'), (11, 3, '4'), (12, 3, '12'),
(13, 4, '1'), (14, 4, '2'), (15, 4, '3'), (16, 4, '4'),
(17, 5, '13'), (18, 5, '12'), (19, 5, '1'), (20, 5, '11'),
(21, 6, '0,1 gam'), (22, 6, '0,01 gam'), (23, 6, '0,001 gam'), (24, 6, '0,0001 gam'),
(25, 7, '12 ml'), (26, 7, '10 ml'), (27, 7, '100 ml'), (28, 7, '1 ml'),
(29, 8, '13'), (30, 8, '12,4'), (31, 8, '12,2'), (32, 8, '12,5'),
(33, 9, '1'), (34, 9, '1,5'), (35, 9, '2'), (36, 9, '3'),
(37, 10, '1'), (38, 10, '2'), (39, 10, '3'), (40, 10, '4'),
(41, 11, '3'), (42, 11, '11'), (43, 11, '7'), (44, 11, '1'),
(45, 12, '3,75'), (46, 12, '4,75'), (47, 12, '5,75'), (48, 12, '6,75'),
(49, 13, 'Tăng'), (50, 13, 'Giảm nhẹ'), (51, 13, 'Giảm mạnh'), (52, 13, 'Không thay đổi'),
(53, 14, '1'), (54, 14, '2'), (55, 14, '3'), (56, 14, '4'),
(57, 15, 'Na₂SO₄'), (58, 15, 'CH₃COONa'), (59, 15, 'NH₄Cl'), (60, 15, 'KCl'),
(61, 16, '0,001 M'), (62, 16, '0,01 M'), (63, 16, '0,0001 M'), (64, 16, '0,00001 M'),
(65, 17, 'pH=1'), (66, 17, 'pH<1'), (67, 17, '[H⁺]>2,0 M'), (68, 17, 'pH>1'),
(69, 18, 'pH=-log[OH⁻]'), (70, 18, 'pH=-log[H⁺]'), (71, 18, 'pH=log[H⁺]'), (72, 18, 'pH=log[OH⁻]'),
(73, 19, 'Acid'), (74, 19, 'Base'), (75, 19, 'Trung tính'), (76, 19, 'Lưỡng tính'),
(77, 20, '10⁻⁷ M'), (78, 20, '10⁷ M'), (79, 20, '10⁻¹⁴ M'), (80, 20, '100 M'),
(81, 21, 'Tăng lên'), (82, 21, 'Giảm xuống'), (83, 21, 'Không đổi'), (84, 21, 'Ban đầu giảm sau đó tăng'),
(85, 22, '12'), (86, 22, '2'), (87, 22, '7'), (88, 22, '10'),
(89, 23, 'pH+pOH=7'), (90, 23, 'pH-pOH=14'), (91, 23, 'pH+pOH=14'), (92, 23, 'pH×pOH=14'),
(93, 24, 'CH₃COOH'), (94, 24, 'H₂S'), (95, 24, 'H₂SO₄'), (96, 24, 'H₂CO₃'),
(97, 25, 'Acid yếu'), (98, 25, 'Acid mạnh'), (99, 25, 'Base yếu'), (100, 25, 'Base mạnh'),
(101, 26, '0'), (102, 26, '7'), (103, 26, '14'), (104, 26, 'Tùy thuộc vào nguồn nước'),
(105, 27, 'Giảm 1 đơn vị'), (106, 27, 'Tăng 1 đơn vị'), (107, 27, 'Giảm 10 đơn vị'), (108, 27, 'Tăng 10 đơn vị'),
(109, 28, 'HCl 0.1 M'), (110, 28, 'NaOH 0.01 M'), (111, 28, 'Nước cất'), (112, 28, 'CH₃COOH 0.1 M'),
(113, 29, 'Máy đo pH'), (114, 29, 'Quỳ tím'), (115, 29, 'Chất chỉ thị màu'), (116, 29, 'Buret'),
(117, 30, '4'), (118, 30, '5'), (119, 30, '3'), (120, 30, '10'),
(121, 31, 'NaOH'), (122, 31, 'NH₃'), (123, 31, 'CH₃COOH'), (124, 31, 'HCl'),
(125, 32, '11'), (126, 32, '9'), (127, 32, '7'), (128, 32, '5'),
(129, 33, '3'), (130, 33, '11'), (131, 33, '7'), (132, 33, '1'),
(133, 34, 'Tăng lên'), (134, 34, 'Giảm xuống'), (135, 34, 'Không đổi'), (136, 34, 'Có thể tăng hoặc giảm'),
(137, 35, 'Dung dịch có pH=7'), (138, 35, 'Dung dịch làm đổi màu quỳ tím'), (139, 35, 'Dung dịch có khả năng giữ pH gần như không đổi khi thêm ít acid hoặc base mạnh'), (140, 35, 'Dung dịch chứa muối và acid mạnh'),
(141, 36, 'HCl và NaCl'), (142, 36, 'NaOH và NaCl'), (143, 36, 'CH₃COOH và CH₃COONa'), (144, 36, 'HNO₃ và NaNO₃'),
(145, 37, 'NH₄Cl và NH₃'), (146, 37, 'H₂CO₃ và NaHCO₃'), (147, 37, 'HCl và NaCl'), (148, 37, 'CH₃COOH và CH₃COONa'),
(149, 38, 'pH=-log[H⁺]'), (150, 38, 'pH=14+log([base]/[acid])'), (151, 38, 'pH=pKa+log([base]/[acid])'), (152, 38, 'pH=pKa-log([base]/[acid])'),
(153, 39, '4,00'), (154, 39, '4,75'), (155, 39, '5,00'), (156, 39, '5,75'),
(157, 40, 'Làm pH tăng mạnh'), (158, 40, 'Làm pH giảm mạnh'), (159, 40, 'Không làm thay đổi pH'), (160, 40, 'Làm pH tăng nhẹ'),
(161, 41, 'HCl/NaCl'), (162, 41, 'CH₃COOH/CH₃COONa'), (163, 41, 'NH₄OH/NH₄Cl'), (164, 41, 'HNO₃/NaNO₃'),
(165, 42, 'Tỉ lệ acid/base=10'), (166, 42, 'pH=7'), (167, 42, 'Tỉ lệ acid/base=1 và pKa gần với pH'), (168, 42, 'Dung dịch loãng'),
(169, 43, '9,25'), (170, 43, '5,25'), (171, 43, '4,75'), (172, 43, '9,75'),
(173, 44, 'NH₃/NH₄Cl'), (174, 44, 'CH₃COOH/CH₃COONa'), (175, 44, 'H₂CO₃/NaHCO₃'), (176, 44, 'NH₄Cl/HCl'),
(177, 45, 'Có khả năng duy trì pH ổn định'), (178, 45, 'Không thay đổi pH khi pha loãng'), (179, 45, 'Bị phá vỡ nếu thêm nhiều acid hoặc base'), (180, 45, 'Gồm 1 acid mạnh và 1 base yếu'),
(181, 46, 'CH₃COOH'), (182, 46, 'CH₃COONa'), (183, 46, 'HCl'), (184, 46, 'NH₄Cl'),
(185, 47, 'Nhiều CH₃COONa hơn'), (186, 47, 'Nhiều CH₃COOH hơn'), (187, 47, 'CH₃COOH=CH₃COONa'), (188, 47, 'Không cần CH₃COOH'),
(189, 48, '4,75'), (190, 48, '5,75'), (191, 48, '3,75'), (192, 48, '6,75'),
(193, 49, 'Duy trì áp suất'), (194, 49, 'Điều chỉnh nhiệt độ'), (195, 49, 'Duy trì pH máu ổn định'), (196, 49, 'Vận chuyển oxi'),
(197, 50, 'Bị đun nóng'), (198, 50, 'Bị pha loãng mạnh'), (199, 50, 'Thêm ít acid hoặc base mạnh'), (200, 50, 'Có pH=7'),
(201, 51, '[base]=[acid]'), (202, 51, '[base] gấp 100 lần [acid]'), (203, 51, 'pKa khắc xa pH'), (204, 51, 'Dung dịch quá loãng'),
(205, 52, 'Acid càng mạnh'), (206, 52, 'Dung dịch càng base'), (207, 52, 'Acid càng yếu'), (208, 52, 'Không liên quan'),
(209, 53, 'Đúng'), (210, 53, 'Sai'),
(211, 54, 'Đúng'), (212, 54, 'Sai'),
(213, 55, 'Đúng'), (214, 55, 'Sai'),
(215, 56, 'Đúng'), (216, 56, 'Sai'),
(217, 57, 'Đúng'), (218, 57, 'Sai'),
(219, 58, 'Đúng'), (220, 58, 'Sai'),
(221, 59, 'Đúng'), (222, 59, 'Sai'),
(223, 60, 'Đúng'), (224, 60, 'Sai'),
(225, 61, 'Đúng'), (226, 61, 'Sai'),
(227, 62, 'Đúng'), (228, 62, 'Sai'),
(229, 63, 'Đúng'), (230, 63, 'Sai'),
(231, 64, 'Đúng'), (232, 64, 'Sai'),
(233, 65, 'Đúng'), (234, 65, 'Sai'),
(235, 66, 'Đúng'), (236, 66, 'Sai'),
(237, 67, 'Đúng'), (238, 67, 'Sai');

-- Insert into question_list table
INSERT INTO question_list (attempts, duration, question_list_id, category, description, difficulty, question_count, title)
VALUES (0, 35, 2, 'Hóa học', 'Các bài tập về chuẩn độ', 'Trung bình', '40', 'Bài tập về thí nghiệm chuẩn độ');

-- Insert into questions table (Multiple Choice Questions)
INSERT INTO questions (answer, question_list_id, question) VALUES
(1, 2, 'Mục đích chính của phép chuẩn độ là gì'),
(1, 2, 'Trong phép chuẩn độ axit-bazơ, dung dịch đã biết nồng độ được gọi là gì'),
(2, 2, 'Điểm tương đương trong phép chuẩn độ là gì'),
(2, 2, 'Chất chỉ thị trong phép chuẩn độ có vai trò gì'),
(1, 2, 'Khi chuẩn độ một axit mạnh bằng một bazo mạnh, pH tại điểm tương đương thường là bao nhiêu (ở 25°C)'),
(2, 2, 'Khi chuẩn độ một axit yếu bằng một bazo mạnh, pH tại điểm tương đương thường là bao nhiêu (ở 25°C)'),
(1, 2, 'Dụng cụ nào sau đây được sử dụng để chứa dung dịch chuẩn (titrant) và nhỏ từ từ vào dung dịch cần chuẩn độ'),
(1, 2, 'Để đảm bảo kết quả chuẩn độ chính xác, cần phải làm gì với buret trước khi sử dụng'),
(0, 2, 'Công thức nào sau đây thường được sử dụng để tính nồng độ của dung dịch cần chuẩn độ sau khi xác định được thể tích tại điểm tương đương'),
(2, 2, 'Sai số chỉ thị là gì trong phép chuẩn độ'),
(1, 2, 'Đường cong chuẩn độ (đồ thị pH theo thể tích chất chuẩn) của axit mạnh với bazo mạnh có đặc điểm gì'),
(3, 2, 'Loại chuẩn độ nào sau đây không sử dụng chất chỉ thị màu mà dựa vào sự thay đổi điện thế để xác định điểm cuối'),
(1, 2, 'Khi chuẩn độ một bazo yếu bằng một axit mạnh, chất chỉ thị nào thường được chọn'),
(2, 2, 'Tại sao nên nhỏ dung dịch chuẩn một cách từ từ và lắc đều bình nón trong quá trình chuẩn độ'),
(1, 2, 'Trong phép chuẩn độ ngược, tại sao cần thêm một lượng dư chính xác chất chuẩn'),
(1, 2, 'Khi chuẩn độ, việc đọc thể tích trên buret phải được thực hiện ở đâu để đảm bảo độ chính xác cao nhất'),
(1, 2, 'Tại sao không nên sử dụng nước cất để tráng bình nón (Erlenmeyer) sau khi đã thêm dung dịch cần chuẩn độ vào và chuẩn bị nhỏ chất chỉ thị'),
(1, 2, 'Khi nào thì nên dừng việc nhỏ dung dịch chuẩn độ vào bình nón'),
(2, 2, 'Nếu trong quá trình chuẩn độ, bạn nhận thấy có bọt khí mắc kẹt ở đầu buret, bạn nên làm gì'),
(0, 2, 'Nếu điểm cuối chuẩn độ của bạn xuất hiện quá sớm so với dự kiến, nguyên nhân nào sau đây có thể xảy ra'),
(1, 2, 'Trong chuẩn độ oxy hóa-khử, chất chỉ thị thường là gì'),
(3, 2, 'Khi chuẩn độ dung dịch HCl bằng dung dịch NaOH, chất nào sau đây có thể được sử dụng làm chất chỉ thị'),
(3, 2, 'Điểm tương đương trong chuẩn độ kết tủa (ví dụ: chuẩn độ AgNO₃ bằng NaCl) được xác định dựa trên cơ sở nào'),
(2, 2, 'Dung dịch chuẩn độ (titrant) cần có những đặc điểm gì để đảm bảo độ chính xác của phép chuẩn độ'),
(2, 2, 'Tại sao cần lắc đều bình nón trong quá trình chuẩn độ'),
(1, 2, 'Độ lặp lại (reproducibility) của phép chuẩn độ được đánh giá như thế nào'),
(0, 2, 'Trong một số trường hợp, cần dung môi trong quá trình chuẩn độ. Mục đích của việc này là gì'),
(1, 2, 'Sai số hệ thống trong phép chuẩn độ có thể do nguyên nhân nào sau đây gây ra'),
(0, 2, 'Nếu dung dịch chuẩn độ có nồng độ thực tế thấp hơn so với nồng độ ghi trên nhãn, kết quả tính toán nồng độ của dung dịch cần chuẩn độ sẽ bị ảnh hưởng như thế nào'),
(1, 2, 'Mục đích của việc sử dụng chất chuẩn gốc (primary standard) trong chuẩn độ là gì'),
(2, 2, 'Một chất được coi là chất chuẩn gốc cần phải có những tính chất gì'),
(2, 2, 'Dung dịch KMnO₄ thường không được sử dụng làm chất chuẩn gốc trực tiếp trong chuẩn độ oxy hóa-khử vì nó có tính chất gì'),
(1, 2, 'Khi chuẩn độ một hỗn hợp axit (ví dụ: HCl và CH₃COOH) bằng một bazo mạnh, đường cong chuẩn độ sẽ có đặc điểm gì'),
(1, 2, 'Tại sao cần phải chuẩn độ lại (re-standardize) một số dung dịch chuẩn độ sau một thời gian bảo quản'),
(1, 2, 'Phép chuẩn độ pH-metry sử dụng thiết bị nào để xác định điểm cuối chuẩn độ'),
(2, 2, 'Trong chuẩn độ tạo phức (complexometric titration), chất tạo phức phổ biến nhất được sử dụng là gì'),
(1, 2, 'Mục đích của việc thêm chất đệm (buffer) vào dung dịch trong một số phép chuẩn độ là gì'),
(1, 2, 'Khi thực hiện chuẩn độ, nếu bạn thấy có bọt khí lớn bám vào thành buret trong quá trình nhỏ dung dịch, bạn nên làm gì'),
(1, 2, 'Yếu tố nào sau đây có thể ảnh hưởng đến độ chính xác của điểm cuối chuẩn độ'),
(2, 2, 'Để giảm thiểu sai số trong chuẩn độ, người thực hiện cần tuân thủ nguyên tắc nào sau đây');

-- Insert into options table (Multiple Choice Questions)
INSERT INTO options (question_id, content) VALUES
(68, 'Xác định pH của dung dịch'), (68, 'Xác định nồng độ chưa biết của một dung dịch'), (68, 'Quan sát sự thay đổi màu sắc của dung dịch'), (68, 'Tạo ra chất mới từ phản ứng hóa học'),
(69, 'Dung dịch cần chuẩn độ (analyt)'), (69, 'Dung dịch chuẩn (titrant)'), (69, 'Dung dịch chỉ thị'), (69, 'Dung dịch đệm'),
(70, 'Điểm mà chất chỉ thị đổi màu'), (70, 'Điểm mà thể tích dung dịch chuẩn thêm vào đạt mức tối đa'), (70, 'Điểm mà số mol chất phản tích phản ứng vừa đủ với số mol chất chuẩn'), (70, 'Điểm mà pH của dung dịch đạt giá trị 7'),
(71, 'Tăng tốc độ phản ứng'), (71, 'Thay đổi nồng độ của dung dịch'), (71, 'Giúp nhận biết điểm tương đương bằng sự thay đổi màu sắc'), (71, 'Tạo ra kết tủa trong dung dịch'),
(72, 'Nhỏ hơn 7'), (72, 'Bằng 7'), (72, 'Lớn hơn 7'), (72, 'Tùy thuộc vào nồng độ ban đầu'),
(73, 'Nhỏ hơn 7'), (73, 'Bằng 7'), (73, 'Lớn hơn 7'), (73, 'Tùy thuộc vào chỉ thị sử dụng'),
(74, 'Pipet'), (74, 'Buret'), (74, 'Erlenmeyer (bình nón)'), (74, 'Cốc thủy tinh'),
(75, 'Tráng bằng nước cất nhiều lần'), (75, 'Tráng bằng dung dịch chuẩn độ vài lần'), (75, 'Sấy khô hoàn toàn'), (75, 'Đổ đầy dung dịch chỉ thị'),
(76, 'C₁V₁=C₂V₂'), (76, 'n₁V₁=n₂V₂'), (76, 'pH=-log[H⁺]'), (76, 'Ka×Kb=Kw'),
(77, 'Sai số do việc đọc thể tích trên buret không chính xác'), (77, 'Sai số do chất chỉ thị không hoạt động'), (77, 'Sự khác biệt giữa điểm tương đương và điểm cuối chuẩn độ'), (77, 'Sai số do nhiệt độ phòng thí nghiệm thay đổi'),
(78, 'Có một bước nhảy pH nhỏ'), (78, 'Có một bước nhảy pH rõ rệt gần pH=7'), (78, 'pH thay đổi đều đặn trong suốt quá trình'), (78, 'Không có bước nhảy pH nào'),
(79, 'Chuẩn độ axit-bazo'), (79, 'Chuẩn độ kết tủa'), (79, 'Chuẩn độ oxy hóa-khử'), (79, 'Chuẩn độ điện thế'),
(80, 'Phenolphtalein (khoảng pH đổi màu: 8.2 - 10.0)'), (80, 'Metyl da cam (khoảng pH đổi màu: 3.1 - 4.4)'), (80, 'Bromthymol xanh (khoảng pH đổi màu: 6.0 - 7.6)'), (80, 'Bất kỳ chỉ thị nào cũng được'),
(81, 'Để phản ứng diễn ra nhanh hơn'), (81, 'Để tránh lãng phí dung dịch chuẩn'), (81, 'Để đảm bảo phản ứng xảy ra hoàn toàn và quan sát sự đổi màu của chỉ thị chính xác'), (81, 'Để làm bay hơi dung môi nhanh hơn'),
(82, 'Để đảm bảo phản ứng xảy ra nhanh'), (82, 'Để định lượng chất không phản ứng trực tiếp hoặc phản ứng chậm'), (82, 'Để tránh sử dụng chất chỉ thị'), (82, 'Để làm tăng pH của dung dịch'),
(83, 'Vị trí mắt ngang với vạch chia trên cùng của dung dịch'), (83, 'Vị trí mắt ngang với vạch chia dưới của mặt khum dung dịch (meniscus)'), (83, 'Vị trí mắt ngang với vạch chia ở giữa của dung dịch'), (83, 'Bất kỳ vị trí nào cũng được, miễn là nhìn rõ'),
(84, 'Vì nước cất sẽ làm thay đổi pH của dung dịch'), (84, 'Vì nước cất sẽ làm loãng nồng độ chất cần chuẩn độ, dẫn đến sai số'), (84, 'Vì nước cất có thể phản ứng với chất chỉ thị'), (84, 'Vì nước cất sẽ làm bình nón bị trơn trượt'),
(85, 'Ngay khi màu sắc của dung dịch trong bình nón bắt đầu thay đổi'), (85, 'Khi màu sắc của dung dịch trong bình nón chuyển hoàn toàn và bền màu trong khoảng 30 giây hoặc hơn'), (85, 'Khi thể tích dung dịch chuẩn độ trong buret giảm xuống một nửa'), (85, 'Khi thấy có bọt khí trong bình nón'),
(86, 'Tiếp tục chuẩn độ vì bọt khí không ảnh hưởng đến kết quả'), (86, 'Ghi lại thể tích và trừ đi thể tích của bọt khí'), (86, 'Loại bỏ bọt khí đó trước khi tiếp tục chuẩn độ'), (86, 'Thay buret khác ngay lập tức'),
(87, 'Nồng độ dung dịch chuẩn độ cao hơn so với giá trị thực'), (87, 'Nồng độ dung dịch cần chuẩn độ cao hơn so với giá trị thực'), (87, 'Bạn đã thêm quá ít chất chỉ thị'), (87, 'Bình nón chứa dung dịch cần chuẩn độ không được tráng sạch'),
(88, 'Một axit yếu hoặc bazo yếu'), (88, 'Một chất có khả năng thay đổi màu sắc khi bị oxy hóa hoặc khử'), (88, 'Một dung môi hữu cơ'), (88, 'Một muối trung hòa'),
(89, 'Metyl da cam'), (89, 'Phenolphtalein'), (89, 'Bromthymol xanh'), (89, 'Tất cả các chất trên'),
(90, 'Sự thay đổi pH của dung dịch'), (90, 'Sự hình thành kết tủa'), (90, 'Sự biến mất của một ion cụ thể hoặc sự hình thành một ion mới'), (90, 'Sự thay đổi màu sắc của chất chỉ thị khi tạo kết tủa phụ'),
(91, 'Nồng độ không cần biết chính xác'), (91, 'Phải có màu sắc rõ ràng'), (91, 'Nồng độ phải được biết chính xác và ổn định'), (91, 'Phải là một chất dễ bay hơi'),
(92, 'Để làm bay hơi dung môi nhanh hơn'), (92, 'Để tránh dung dịch bị nóng lên'), (92, 'Để đảm bảo dung dịch chuẩn độ được trộn đều và phản ứng xảy ra hoàn toàn'), (92, 'Để ngăn chặn sự hình thành bọt khí'),
(93, 'Bằng cách thực hiện một lần duy nhất và ghi lại kết quả'), (93, 'Bằng cách thực hiện nhiều lần và kiểm tra sự sai khác giữa các kết quả'), (93, 'Bằng cách thay đổi các điều kiện thí nghiệm'), (93, 'Bằng cách so sánh kết quả với một phòng thí nghiệm khác'),
(94, 'Tăng tốc độ phản ứng'), (94, 'Làm giảm thể tích dung dịch'), (94, 'Làm bay hơi chất chỉ thị'), (94, 'Tăng độ hòa tan của kết tủa'),
(95, 'Lỗi do người thực hiện đọc thể tích không chính xác'), (95, 'Cân không chính xác khối lượng chất chuẩn gốc'), (95, 'Nhiệt độ phòng thí nghiệm dao động đột ngột'), (95, 'Bọt khí trong buret không được loại bỏ hoàn toàn'),
(96, 'Cao hơn so với giá trị thực'), (96, 'Thấp hơn so với giá trị thực'), (96, 'Không bị ảnh hưởng'), (96, 'Không thể xác định được'),
(97, 'Để tạo ra phản ứng phụ'), (97, 'Để chuẩn hóa nồng độ của dung dịch chuẩn'), (97, 'Để làm tăng màu sắc của dung dịch'), (97, 'Để ngăn chặn sự phân hủy của dung dịch'),
(98, 'Độ tinh khiết thấp, không ổn định'), (98, 'Khối lượng mol nhỏ, dễ bay hơi'), (98, 'Độ tinh khiết cao, ổn định, không hút ẩm, không phản ứng với không khí'), (98, 'Có khả năng phản ứng với nhiều chất khác nhau'),
(99, 'Rất đắt tiền'), (99, 'Không màu'), (99, 'Không ổn định, dễ bị phân hủy bởi ánh sáng và tạp chất hữu cơ'), (99, 'Khó hòa tan trong nước'),
(100, 'Chỉ có một bước nhảy pH duy nhất'), (100, 'Có hai bước nhảy pH riêng biệt'), (100, 'pH thay đổi tuyến tính'), (100, 'Không có bước nhảy pH nào'),
(101, 'Để tiết kiệm hóa chất'), (101, 'Vì dung dịch có thể bị phân hủy hoặc bay hơi, làm thay đổi nồng độ'), (101, 'Để thay đổi loại chất chỉ thị'), (101, 'Để điều chỉnh pH của dung dịch'),
(102, 'Quang kế (spectrophotometer)'), (102, 'Máy đo pH (pH meter)'), (102, 'Máy đo độ dẫn điện (conductivity meter)'), (102, 'Cân phân tích'),
(103, 'Natri clorua (NaCl)'), (103, 'Axit clohidric (HCl)'), (103, 'EDTA (Ethylenediaminetetraacetic acid)'), (103, 'Kali permanganat (KMnO₄)'),
(104, 'Làm tăng tốc độ phản ứng'), (104, 'Duy trì pH ổn định trong một khoảng nhất định'), (104, 'Tạo ra màu sắc để quan sát'), (104, 'Tăng nồng độ chất phản ứng'),
(105, 'Bỏ qua và tiếp tục sử dụng'), (105, 'Dừng lại, gõ nhẹ vào thành để bọt thoát ra, sau đó tiếp tục'), (105, 'Lắc mạnh để làm tan bọt'), (105, 'Đổ hết dung dịch và bắt đầu lại'),
(106, 'Kích thước của bình thử'), (106, 'Tốc độ thêm dung dịch chuẩn'), (106, 'Ánh sáng phòng thí nghiệm'), (106, 'Màu sắc của bàn làm việc'),
(107, 'Đọc thể tích nhanh chóng để tiết kiệm thời gian'), (107, 'Sử dụng một lượng lớn chất chỉ thị để chuẩn độ chính xác hơn'), (107, 'Đảm bảo tất cả các dụng cụ đều sạch sẽ và được tráng đúng cách'), (107, 'Luôn luôn sử dụng cùng một loại dung dịch chuẩn độ cho');